name: AWS OIDC Test

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
#   contents: read

jobs:
  test-aws:
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get OIDC claims
        shell: bash
        run: |
          set -e

          echo "Requesting GitHub OIDC token..."

          RESPONSE=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

          echo "OIDC response received"

          # Extract token without jq
          ID_TOKEN=$(python3 -c '
          import sys, json
          data=json.load(sys.stdin)
          print(data["value"])
          ' <<< "$RESPONSE")

          echo "OIDC token received successfully"

          # Extract JWT payload
          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f 2)

          # Decode JWT payload
          python3 -c '
          import sys
          import base64
          import json

          payload = sys.stdin.read().strip()

          payload += "=" * (-len(payload) % 4)

          decoded = base64.urlsafe_b64decode(payload)

          claims = json.loads(decoded)

          print("")
          print("========== OIDC CLAIMS ==========")
          print("iss :", claims.get("iss"))
          print("aud :", claims.get("aud"))
          print("sub :", claims.get("sub"))
          print("repository :", claims.get("repository"))
          print("repository_id :", claims.get("repository_id"))
          print("repository_owner :", claims.get("repository_owner"))
          print("repository_owner_id :", claims.get("repository_owner_id"))
          print("ref :", claims.get("ref"))
          print("event_name :", claims.get("event_name"))
          print("=================================")
          ' <<< "$PAYLOAD"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::772412007802:role/github-actions-prod-deploy
          role-session-name: github-actions
          aws-region: ap-south-2

      - name: Check AWS identity
        run: aws sts get-caller-identity
